export const QuestionsList = [
  {
    question: "If you were signing a message using RSA, you would use the:",
    answersList: [
      { answer: "Private Key", isCorrect: true },
      { answer: "Public Key", isCorrect: false },
    ]
  },
  {
    question: "Private Key",
    answersList: [
      { answer: "Private Key", isCorrect: false },
      { answer: "Public Key", isCorrect: true },
    ]
  },
  {
    question: "Fill in the blank: “the keystream generated by a stream cypher must appear ___”",
    answersList: [
      { answer: "Statically random", isCorrect: true },
      { answer: "Logically Random ", isCorrect: false },
      { answer: "Statically Linear ", isCorrect: false },
      { answer: "Logically Linear ", isCorrect: false },
    ]
  },
  {
    question: "What is a type of cryptography? ",
    answersList: [
      { answer: "Reflective ", isCorrect: false },
      { answer: "Reflexive ", isCorrect: false },
      { answer: "Symmetric ", isCorrect: true },
    ]
  },
  {
    question: "Message Authentication Codes provide which of the following: ",
    answersList: [
      { answer: "Integrity and authenticity ", isCorrect: true },
      { answer: "Integrity  ", isCorrect: false },
      { answer: "Authenticity and confidentiality ", isCorrect: false },
      { answer: "Confidentiality  ", isCorrect: false },
    ]
  },
  {
    question: "What are hash functions used for? ",
    answersList: [
      { answer: "Generating cyphers ", isCorrect: false },
      { answer: "Digital Signatures ", isCorrect: true },
      { answer: "Sending messages ", isCorrect: false },
      { answer: "None of the above ", isCorrect: false },
    ]
  },
  {
    question: "Which is the strongest cryptographic attack? ",
    answersList: [
      { answer: "chosen plaintext ", isCorrect: false },
      { answer: "chosen cipher text", isCorrect: true },
      { answer: "Brute Force ", isCorrect: false },
      { answer: "Related key attack ", isCorrect: false },
    ]
  },
  {
    question: "Which is the weakest cryptographic attack ",
    answersList: [
      { answer: "Related key attack ", isCorrect: false },
      { answer: "Brute force ", isCorrect: true },
      { answer: "Chosen plain text ", isCorrect: false },
      { answer: "known plain text ", isCorrect: false },
    ]
  },
  {
    question: "Is public key cryptography symmetric or asymmetric? ",
    answersList: [
      { answer: "Asymmetric  ", isCorrect: true },
      { answer: "Symmetric ", isCorrect: false },
    ]
  },
  {
    question: "What is not a disadvantage of stream ciphers? ",
    answersList: [
      { answer: "keystream must appear statistically random  ", isCorrect: false },
      { answer: "You must never reuse a key ", isCorrect: false },
      { answer: "Steam ciphers do not protect the cipher text ", isCorrect: false },
      { answer: "low memory footprint ", isCorrect: true },
    ]
  },
  
];
